### ISSUE TITLE
flightmon

### ISSUE THREAD

**Issue by mik3y** [rickstaa/awesome-adsb#7]
### Link to suggestion

https://github.com/mik3y/flightmon

### Describe your suggesiton

Hey! (Thanks so much for this repo, found some cool new toys.)

Suggesting, but not quite confident enough that it is "awesome", a tiny little tool I wrote, `flightmon`.

Wrote it mostly for "ssh into the pi and make sure the stack is all working" - but I figured it might be a simple/skeletal project for anyone with a more ambitious project idea in the neighborhood.

**Comment by rickstaa** [comment]
Hey @mik3y. What a fantastic little tool! Thanks for bringing it to my attention :dark_sunglasses:. We can add it under https://github.com/rickstaa/awesome-adsb#visualisation and rename that section `Data Visualization`. What do you think? Would it be possible to create a pull request so that I can merge it into the main branch?

**Comment by rickstaa** [comment]
@mik3y I found some time to add your tool in https://github.com/rickstaa/awesome-adsb/releases/tag/v1.0.24. It is now live on the site. Feel free to let me know if you want me to change anything.

**Comment by mik3y** [comment]
Hey, that's rad! You beat me to it (the PR) - thanks for doing that. Looks awesome. Cheers!
